export const COUNTRIES = [
  "Türkiye",
  "Afganistan",
  "Almanya",
  "Amerika Birleşik Devletleri",
  "Andorra",
  "Angola",
  "Antigua ve Barbuda",
  "Arjantin",
  "Arnavutluk",
  "Avustralya",
  "Avusturya",
  "Azerbaycan",
  "Bahamalar",
  "Bahreyn",
  "Bangladeş",
  "Barbados",
  "Belçika",
  "Belize",
  "Benin",
  "Beyaz Rusya",
  "Bhutan",
  "Birleşik Arap Emirlikleri",
  "Birleşik Krallık",
  "Bolivya",
  "Bosna Hersek",
  "Botsvana",
  "Brezilya",
  "Brunei",
  "Bulgaristan",
  "Burkina Faso",
  "Burundi",
  "Cezayir",
  "Cibuti",
  "Çad",
  "Çek Cumhuriyeti",
  "Çin",
  "Danimarka",
  "Demokratik Kongo Cumhuriyeti",
  "Dominik Cumhuriyeti",
  "Dominika",
  "Ekvador",
  "Ekvator Ginesi",
  "El Salvador",
  "Endonezya",
  "Eritre",
  "Ermenistan",
  "Estonya",
  "Esvatini",
  "Etiyopya",
  "Fas",
  "Fiji",
  "Fildişi Sahili",
  "Filipinler",
  "Finlandiya",
  "Fransa",
  "Gabon",
  "Gambiya",
  "Gana",
  "Gine",
  "Gine-Bissau",
  "Grenada",
  "Guatemala",
  "Guyana",
  "Güney Afrika",
  "Güney Kore",
  "Güney Sudan",
  "Gürcistan",
  "Haiti",
  "Hindistan",
  "Hırvatistan",
  "Hollanda",
  "Honduras",
  "Irak",
  "İran",
  "İrlanda",
  "İspanya",
  "İsrail",
  "İsveç",
  "İsviçre",
  "İtalya",
  "İzlanda",
  "Jamaika",
  "Japonya",
  "Kamboçya",
  "Kamerun",
  "Kanada",
  "Karadağ",
  "Katar",
  "Kazakistan",
  "Kenya",
  "Kırgızistan",
  "Kiribati",
  "Kolombiya",
  "Komorlar",
  "Kongo Cumhuriyeti",
  "Kosova",
  "Kosta Rika",
  "Küba",
  "Kuveyt",
  "Kuzey Kıbrıs",
  "Kuzey Kore",
  "Kuzey Makedonya",
  "Laos",
  "Lesoto",
  "Letonya",
  "Lübnan",
  "Liberya",
  "Libya",
  "Liechtenstein",
  "Litvanya",
  "Lüksemburg",
  "Macaristan",
  "Madagaskar",
  "Malavi",
  "Maldivler",
  "Malezya",
  "Mali",
  "Malta",
  "Marshall Adaları",
  "Mauritius",
  "Meksika",
  "Mikronezya",
  "Mısır",
  "Moğolistan",
  "Moldova",
  "Monako",
  "Moritanya",
  "Mozambik",
  "Myanmar",
  "Namibya",
  "Nauru",
  "Nepal",
  "Nijer",
  "Nijerya",
  "Nikaragua",
  "Norveç",
  "Orta Afrika Cumhuriyeti",
  "Özbekistan",
  "Pakistan",
  "Palau",
  "Filistin",
  "Panama",
  "Papua Yeni Gine",
  "Paraguay",
  "Peru",
  "Polonya",
  "Portekiz",
  "Romanya",
  "Ruanda",
  "Rusya",
  "Saint Kitts ve Nevis",
  "Saint Lucia",
  "Saint Vincent ve Grenadinler",
  "Samoa",
  "San Marino",
  "São Tomé ve Príncipe",
  "Senegal",
  "Sırbistan",
  "Sierra Leone",
  "Singapur",
  "Slovakya",
  "Slovenya",
  "Solomon Adaları",
  "Somali",
  "Sri Lanka",
  "Sudan",
  "Surinam",
  "Suriye",
  "Suudi Arabistan",
  "Şili",
  "Tacikistan",
  "Tanzanya",
  "Tayland",
  "Tayvan",
  "Togo",
  "Tonga",
  "Trinidad ve Tobago",
  "Tunus",
  "Tuvalu",
  "Türkmenistan",
  "Uganda",
  "Ukrayna",
  "Umman",
  "Uruguay",
  "Ürdün",
  "Vanuatu",
  "Vatikan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yeni Zelanda",
  "Yunanistan",
  "Zambiya",
  "Zimbabve"
];
