export const COUNTRIES = [
  "Türkiye",
  "Almanya",
  "Amerika Birleşik Devletleri",
  "Arjantin",
  "Arnavutluk",
  "Avustralya",
  "Avusturya",
  "Azerbaycan",
  "Bahreyn",
  "Belçika",
  "Beyaz Rusya",
  "Birleşik Arap Emirlikleri",
  "Birleşik Krallık",
  "Bosna Hersek",
  "Brezilya",
  "Bulgaristan",
  "Cezayir",
  "Çek Cumhuriyeti",
  "Çin",
  "Danimarka",
  "Endonezya",
  "Estonya",
  "Fas",
  "Filipinler",
  "Finlandiya",
  "Fransa",
  "Güney Afrika",
  "Güney Kore",
  "Gürcistan",
  "Hindistan",
  "Hırvatistan",
  "Hollanda",
  "Irak",
  "İran",
  "İrlanda",
  "İspanya",
  "İsrail",
  "İsveç",
  "İsviçre",
  "İtalya",
  "Japonya",
  "Kanada",
  "Katar",
  "Kazakistan",
  "Kosova",
  "Kuzey Kıbrıs",
  "Kuzey Makedonya",
  "Küba",
  "Kuveyt",
  "Letonya",
  "Libya",
  "Litvanya",
  "Lüksemburg",
  "Macaristan",
  "Malezya",
  "Meksika",
  "Mısır",
  "Moğolistan",
  "Moldova",
  "Norveç",
  "Özbekistan",
  "Pakistan",
  "Polonya",
  "Portekiz",
  "Romanya",
  "Rusya",
  "Sırbistan",
  "Singapur",
  "Slovakya",
  "Slovenya",
  "Suudi Arabistan",
  "Şili",
  "Tayland",
  "Tayvan",
  "Tunus",
  "Türkmenistan",
  "Ukrayna",
  "Umman",
  "Ürdün",
  "Vietnam",
  "Yeni Zelanda",
  "Yunanistan"
];
