import type { OrderItem, Product, ProductVariant } from "@shared/schema";

type SkuVariant = Pick<ProductVariant, "id" | "sku" | "size" | "color">;

/**
 * Recognize only the templates generated by this app and its importer.
 * A matching prefix alone is not proof that a code is generated.
 */
export function planVariantSkuUpdates(
  oldSku: string | null,
  newSku: string | null,
  variants: SkuVariant[],
): Array<{ id: string; sku: string | null }> {
  if (!oldSku || oldSku === newSku) return [];
  return variants.flatMap(variant => {
    if (!variant.sku) return [];
    const suffixes = new Set([""]);
    if (variant.size) suffixes.add(`-${variant.size}`);
    if (variant.color) suffixes.add(`-${variant.color}`);
    if (variant.size && variant.color) {
      suffixes.add(`-${variant.size}-${variant.color}`);
    }
    const suffix = Array.from(suffixes).find(value => variant.sku === `${oldSku}${value}`);
    if (suffix === undefined) return [];
    return [{ id: variant.id, sku: newSku ? `${newSku}${suffix}` : null }];
  });
}

type CatalogReader = {
  getProductVariant(id: string): Promise<ProductVariant | undefined>;
  getProduct(id: string): Promise<Product | undefined>;
};

type OrderCatalogItem = Pick<OrderItem, "id" | "productId" | "variantId">;

/** Both old and new orders use the current parent product code without suffixes. */
export async function getOrderItemCatalogDetails(
  item: OrderCatalogItem,
  catalog: CatalogReader,
): Promise<{ sku: string | null; productImage: string | null }> {
  const variant = item.variantId
    ? await catalog.getProductVariant(item.variantId)
    : undefined;
  let product = item.productId ? await catalog.getProduct(item.productId) : undefined;
  if (!product && variant?.productId && variant.productId !== item.productId) {
    product = await catalog.getProduct(variant.productId);
  }
  return {
    sku: product?.sku?.trim() ? product.sku : variant?.sku?.trim() ? variant.sku : null,
    productImage: product?.images?.[0] || null,
  };
}

/** Invoice and order-detail codes share the same current catalog resolution. */
export async function getOrderItemSkus(
  items: OrderCatalogItem[],
  catalog: CatalogReader,
): Promise<Map<string, string>> {
  const entries = await Promise.all(items.map(async item => {
    const { sku } = await getOrderItemCatalogDetails(item, catalog);
    return [item.id, sku] as const;
  }));
  return new Map(entries.filter((entry): entry is readonly [string, string] => !!entry[1]));
}
