import type { OrderItem, Product, ProductVariant } from "@shared/schema";

type SkuVariant = Pick<ProductVariant, "id" | "sku" | "size" | "color">;

/**
 * Recognize only the templates generated by this app and its importer.
 * A matching prefix alone is not proof that a code is generated.
 */
export function planVariantSkuUpdates(
  oldSku: string | null,
  newSku: string | null,
  variants: SkuVariant[],
): Array<{ id: string; sku: string | null }> {
  if (!oldSku || oldSku === newSku) return [];
  return variants.flatMap(variant => {
    if (!variant.sku) return [];
    const suffixes = new Set([""]);
    if (variant.size) suffixes.add(`-${variant.size}`);
    if (variant.color) suffixes.add(`-${variant.color}`);
    if (variant.size && variant.color) {
      suffixes.add(`-${variant.size}-${variant.color}`);
    }
    const suffix = Array.from(suffixes).find(value => variant.sku === `${oldSku}${value}`);
    if (suffix === undefined) return [];
    return [{ id: variant.id, sku: newSku ? `${newSku}${suffix}` : null }];
  });
}

type CatalogReader = {
  getProductVariant(id: string): Promise<ProductVariant | undefined>;
  getProduct(id: string): Promise<Product | undefined>;
};

/** Invoice codes are keyed by order item, including items without a variant. */
export async function getOrderItemSkus(
  items: Pick<OrderItem, "id" | "productId" | "variantId">[],
  catalog: CatalogReader,
): Promise<Map<string, string>> {
  const entries = await Promise.all(items.map(async item => {
    const variant = item.variantId
      ? await catalog.getProductVariant(item.variantId)
      : undefined;
    if (variant?.sku?.trim()) return [item.id, variant.sku] as const;
    const productId = variant?.productId || item.productId;
    const product = productId ? await catalog.getProduct(productId) : undefined;
    return [item.id, product?.sku?.trim() ? product.sku : null] as const;
  }));
  return new Map(entries.filter((entry): entry is readonly [string, string] => !!entry[1]));
}
