import type { OrderItem, Product, ProductVariant } from "@shared/schema";

type SkuVariant = Pick<ProductVariant, "id" | "sku" | "size" | "color">;

function variantSuffixes(variant: SkuVariant): string[] {
  const suffixes: string[] = [];
  if (variant.size && variant.color) suffixes.push(`-${variant.size}-${variant.color}`);
  if (variant.size) suffixes.push(`-${variant.size}`);
  if (variant.color) suffixes.push(`-${variant.color}`);
  return suffixes;
}

/**
 * Recognize only the templates generated by this app and its importer.
 * A matching prefix alone is not proof that a code is generated.
 */
export function planVariantSkuUpdates(
  oldSku: string | null,
  newSku: string | null,
  variants: SkuVariant[],
): Array<{ id: string; sku: string | null }> {
  if (!oldSku || oldSku === newSku) return [];
  return variants.flatMap(variant => {
    if (!variant.sku) return [];
    const suffix = [...variantSuffixes(variant), ""]
      .find(value => variant.sku === `${oldSku}${value}`);
    if (suffix === undefined) return [];
    return [{ id: variant.id, sku: newSku ? `${newSku}${suffix}` : null }];
  });
}

export function buildVariantSkuCheck(
  product: Pick<Product, "id" | "name" | "sku">,
  variants: SkuVariant[],
) {
  return {
    product: { id: product.id, name: product.name, sku: product.sku },
    variants: variants.map(variant => {
      const suffixes = variantSuffixes(variant);
      const base = { id: variant.id, size: variant.size, color: variant.color, currentSku: variant.sku };
      if (!product.sku?.trim()) {
        return { ...base, suggestedSku: null, status: "custom" as const, needsUpdate: false };
      }
      if ([...suffixes, ""].some(suffix => variant.sku === `${product.sku}${suffix}`)) {
        return { ...base, suggestedSku: variant.sku, status: "current" as const, needsUpdate: false };
      }
      // An old size/color suffix suggests a generated code, but is not proof.
      // Repairs therefore require reviewing and selecting the exact old/new pair.
      const suffix = !variant.sku?.trim() ? (suffixes[0] || "")
        : suffixes.find(value => variant.sku!.length > value.length && variant.sku!.endsWith(value));
      if (suffix !== undefined) {
        return { ...base, suggestedSku: `${product.sku}${suffix}`, status: "candidate" as const, needsUpdate: true };
      }
      return { ...base, suggestedSku: null, status: "custom" as const, needsUpdate: false };
    }),
  };
}

export type VariantSkuCheck = ReturnType<typeof buildVariantSkuCheck>;

/** One catalog-wide preview, no writes and no guesses without user approval. */
export function buildBulkVariantSkuCheck(
  products: Pick<Product, "id" | "name" | "sku">[],
  variants: (SkuVariant & { productId: string })[],
) {
  const variantsByProduct = new Map<string, SkuVariant[]>();
  for (const variant of variants) {
    const group = variantsByProduct.get(variant.productId) || [];
    group.push(variant);
    variantsByProduct.set(variant.productId, group);
  }
  const checks = products.map(product =>
    buildVariantSkuCheck(product, variantsByProduct.get(product.id) || []),
  );
  const checkedVariants = checks.flatMap(check => check.variants);
  return {
    checkedProducts: products.length,
    totalVariants: checkedVariants.length,
    candidateCount: checkedVariants.filter(row => row.status === "candidate").length,
    currentCount: checkedVariants.filter(row => row.status === "current").length,
    customCount: checkedVariants.filter(row => row.status === "custom").length,
    missingSkuProducts: products.filter(product => !product.sku?.trim()).length,
    products: checks.filter(check => check.variants.some(row => row.needsUpdate)),
  };
}

export type BulkVariantSkuCheck = ReturnType<typeof buildBulkVariantSkuCheck>;
export type VariantSkuRepairSelection = {
  id: string;
  expectedCurrentSku: string | null;
  expectedSuggestedSku: string;
};

export class SkuRepairError extends Error {
  constructor(public status: number, message: string) {
    super(message);
    this.name = "SkuRepairError";
  }
}

type CatalogReader = {
  getProductVariant(id: string): Promise<ProductVariant | undefined>;
  getProduct(id: string): Promise<Product | undefined>;
};

type OrderCatalogItem = Pick<OrderItem, "id" | "productId" | "variantId">;

/** Use the live variant code, including size/color suffixes, for old and new orders. */
export async function getOrderItemCatalogDetails(
  item: OrderCatalogItem,
  catalog: CatalogReader,
): Promise<{ sku: string | null; productImage: string | null }> {
  const variant = item.variantId
    ? await catalog.getProductVariant(item.variantId)
    : undefined;
  let product = item.productId ? await catalog.getProduct(item.productId) : undefined;
  if (!product && variant?.productId && variant.productId !== item.productId) {
    product = await catalog.getProduct(variant.productId);
  }
  return {
    sku: variant?.sku?.trim() ? variant.sku : product?.sku?.trim() ? product.sku : null,
    productImage: product?.images?.[0] || null,
  };
}

/** Invoice and order-detail codes share the same current catalog resolution. */
export async function getOrderItemSkus(
  items: OrderCatalogItem[],
  catalog: CatalogReader,
): Promise<Map<string, string>> {
  const entries = await Promise.all(items.map(async item => {
    const { sku } = await getOrderItemCatalogDetails(item, catalog);
    return [item.id, sku] as const;
  }));
  return new Map(entries.filter((entry): entry is readonly [string, string] => !!entry[1]));
}
